### ISSUE TITLE
Implement NFT selection section on second page

### ISSUE THREAD

**Issue by abdelhakeem** [abdelhakeem/nft-mutator#7]

**Comment by RajGM** [comment]
Hi @abdelhakeem 
What's the difference between #7 and #8

**Comment by abdelhakeem** [comment]
> Hi @abdelhakeem What's the difference between #7 and #8

![sections](https://user-images.githubusercontent.com/20467669/181371855-2eb2f3d6-cabb-424c-9fe1-c25c71867e4d.png)

The first is the NFT selection section (#7), the second is the NFT editor section (#8).

**Comment by RajGM** [comment]
![picker](https://user-images.githubusercontent.com/16620150/183065818-c068b038-4bb4-40ac-bc7b-9055f5a3c14c.png)

Looking as expected

**Comment by RajGM** [comment]
#27
